### ISSUE TITLE
Exception at Instrumentation

### ISSUE THREAD

**Issue by lolobosse** [secure-software-engineering/DroidForce#5]
I changed my SDK few days ago for professional reason and reinstalled it. Tried to instrument from Eclipse as well from my Server and I get this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
    at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:91)
    at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:72)
    at soot.DexClassProvider.classesOfDex(DexClassProvider.java:121)
    at soot.DexClassProvider.readDexFile(DexClassProvider.java:97)
    at soot.DexClassProvider.buildDexIndex(DexClassProvider.java:88)
    at soot.DexClassProvider.find(DexClassProvider.java:56)
    at soot.SourceLocator.getClassSource(SourceLocator.java:75)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:209)
    at soot.SootResolver.bringToSignatures(SootResolver.java:266)
    at soot.SootResolver.bringToBodies(SootResolver.java:304)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:167)
    at soot.SootResolver.resolveClass(SootResolver.java:131)
    at soot.Scene.tryLoadClass(Scene.java:679)
    at soot.Scene.loadBasicClasses(Scene.java:1339)
    at soot.Scene.loadNecessaryClasses(Scene.java:1418)
    at de.ecspride.Settings.initialiseSoot(Settings.java:120)
    at de.ecspride.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 17 more
```

I guess that this error only happens on my installation but it would kind of critical that I success in solving it? Does someone has an idea? It appears to be related to `guava` but this library is exported in the `heros` project...

**Comment by Alexandre-Bartel** [comment]
Have you tried to update heros? This should fix the issue.
